### ISSUE TITLE
Build snapweb

### ISSUE THREAD

**Issue by infeeeee** [Saiyato/snapserver_docker#2]
https://github.com/Saiyato/snapserver_docker/blob/56c5bcd8e7f6090dd4e87112ed54ce21fe188d0f/Dockerfile#L14

Inside the container I can see *.ts files, but should be js. According to snapweb docs, you should build snapweb, and copy from the dist folder: https://github.com/badaix/snapweb I guess this step is missing from the docker files.

**Comment by squat** [comment]
Fixed by #4 :) i guess this can be closed
