### ISSUE TITLE
404 for libflac.js

### ISSUE THREAD

**Issue by squat** [Saiyato/snapserver_docker#6]
Hi I think there is something funny in the latest Docker containers. When opening the snapweb UI, I see a 404 for libflac.js.
The browser is trying to load the file from `/3rd-party/libflac.js`, which should translate to `/var/www/html/3rd-party/libflac.js` in the container. Indeed, when I inspect the Docker container manually, the file is located incorrectly one directory higher, i.e. directly at `/var/www/html/libflac.js`:
```shell
$ docker run --rm --entrypoint=sh saiyato/snapserver -c 'ls /var/www/html'
config.js
config.js.map
favicon.ico
index.html
launcher-icon.png
libflac.js
manifest.json
mute_icon.png
play.png
snapcontrol.js
snapcontrol.js.map
snapstream.js
snapstream.js.map
speaker_icon.png
stop.png
styles.css
```

Curiously, when I build the Dockerfile manually, the libflac.js file ends up in the correct location. Perhaps this could be solved by triggering a rebuild of the containers?

**Comment by Saiyato** [comment]
Hi,

I rebuilt all images, and couldn't reproduce this, can you check if rebuilding fixed the issue? :)

**Comment by squat** [comment]
I just tried pulling and running the same command and can still reproduce the issue. As far as I can tell, the file is still located in the wrong directory:
```shell
squat ~/downloads ➜ docker pull saiyato/snapserver
Using default tag: latest
latest: Pulling from saiyato/snapserver
97518928ae5f: Already exists
7d3483a9a0e2: Pull complete
ca1ccd4cd574: Pull complete
14375722c205: Pull complete
ae7ce7f48135: Pull complete
fbc2f03f2b04: Pull complete
Digest: sha256:7323d5a20fb9bf83a53f5ec0965a446382a07099bd906d5af38f12a3c5372289
Status: Downloaded newer image for saiyato/snapserver:latest
docker.io/saiyato/snapserver:latest

squat ~/downloads ➜ docker run --rm --entrypoint=sh saiyato/snapserver -c 'ls /var/www/html'
config.js
config.js.map
favicon.ico
index.html
launcher-icon.png
libflac.js
manifest.json
mute_icon.png
play.png
snapcontrol.js
snapcontrol.js.map
snapstream.js
snapstream.js.map
speaker_icon.png
stop.png
styles.css
```

Note: libflac.js is still at the root of the HTML directory instead of where it should be, i.e. `3rd-party/libflac.js`

**Comment by Saiyato** [comment]
Hmmmm, it is built according to specs, I will recheck

**Comment by Saiyato** [comment]
I really don't get it, when manually building the image.... it copies libflac.js to 3rd-party. I did improve the dockerfile to support multi-arch building. I will check the file thoroughly

**Comment by squat** [comment]
Yes exactly, when I `docker build .` then the files end up in the right place too. I wonder if the CI you are using is somehow using an old version of the Dockerfile?

**Comment by Saiyato** [comment]
That shouldn't be it, I'm building the containers manually :wink: But... I did change quite a lot:

+ Multi-arch building
+ Multistage builds

Update: building again now using the build-script and the latest Dockerfile. Manual tests still show the 3rd-party directory where it should be.

**Comment by Saiyato** [comment]
Found the problem! At least I think... it's still building now. I will post back in about 15-25 minutes (rough estimate)

If you copy files from another stage in a multistage builder, you shouldn't use the asterix (*), because that will kill your original folder structure.

Update: confirmed! I will rebuild for all architectures, then push to Docker Hub (this will take a while though, the arm versions take some time).

**Comment by Saiyato** [comment]
Just pushed new images for all architectures, this solves this problem. I will also push my new build scripts, so people can collaborate and improve on those :wink:

**Comment by Saiyato** [comment]
See commit cb004ca5346248fc1f8ebcba9f6ede83ee4af3ba

**Comment by squat** [comment]
Thanks :) indeed everything works now
